# The bottom 3 layers of each tube are hidden at the start of
# the game and are only revealed after clearing the layer on
# top of them.
tubes = [
    ['pink', 'blue', 'orange', 'green'],
    ['pink', 'blue', 'green', 'orange'],
    ['red', 'orange', 'red', 'pink'],
    ['blue', 'red', 'pink', 'orange'],
    ['blue', 'red', 'green', 'green'],
    [],
    [],
]