tubes = [
    ['green', 'green', 'green', 'red'],
    ['green', 'pink', 'red', 'orange'],
    ['orange', 'red', 'orange', 'pink'],
    ['pink', 'orange', 'pink', 'blue'],
    ['red', 'blue', 'blue', 'blue'],
    [],
    [],
]