tubes = [
    ['orange', 'red', 'orange', 'green'],
    ['orange', 'red', 'blue', 'blue'],
    ['orange', 'blue', 'pink', 'pink'],
    ['blue', 'red', 'pink', 'green'],
    ['pink', 'green', 'red', 'green'],
    [],
    [],
]