tubes = [
    [
        "382ebb",
        "81d385",
        "db9051",
        "81d385",
    ],
    [
        "db9051",
        "d9677c",
        "d9677c",
        "db9051",
    ],
    [
        "b5392d",
        "382ebb",
        "b5392d",
        "d9677c",
    ],
    [
        "d9677c",
        "81d385",
        "b5392d",
        "382ebb",
    ],
    [
        "db9051",
        "b5392d",
        "81d385",
        "382ebb",
    ],
    [
        "empty",
        "empty",
        "empty",
        "empty",
    ],
    [
        "empty",
        "empty",
        "empty",
        "empty",
    ],
]
